buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}

plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
}

apply plugin: 'org.spongepowered.mixin'

group = mod_group_id
version = mod_version

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

minecraft {
    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = true


    runs {

        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }

        gameTestServer {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        data {
            workingDirectory project.file('run-data')
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"

    config "${mod_id}.mixins.json"
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {
        url "https://cursemaven.com"
    }
    mavenCentral()
}

dependencies {

    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    //implementation fg.deobf("curse.maven:free-cam-557076:4643128")

//    implementation fg.deobf("curse.maven:viltrumite-1553010:8677178")
//    implementation fg.deobf("curse.maven:viltrumite-flight-1528087:8642587")

    implementation fg.deobf("curse.maven:worldedit-225608:4586218")

    //simple clouds test
    //implementation fg.deobf("curse.maven:simple-clouds-1121215:6928978")
    //implementation fg.deobf("curse.maven:better-clouds-1285973:7074847")

    //testing with other mods
//    implementation fg.deobf("curse.maven:jade-324717:8479276")
    //implementation fg.deobf("curse.maven:embeddium-908741:5681725")
    //runtimeOnly("curse.maven:oculus-581495:6020961")


}

//processResources {
//
//    doLast {
//        def source = file("$destinationDir/assets/tsp/shaders/include/shading/light.glsl")
//        def targetDir = file("$destinationDir/assets/minecraft/shaders/include")
//        def target = file("$targetDir/light.glsl")
//
//        if (source.exists()) {
//            targetDir.mkdirs()
//            target.text = source.text
//            println "[TSP] light.glsl duplicato in assets/minecraft/shaders/include/ per l'override vanilla"
//        } else {
//            println "[TSP] Và CHIaaannne': la sorgente light.glsl non trovata in ${source} - override NON applicato"
//        }
//    }
//}


tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [minecraft_version   : minecraft_version, minecraft_version_range: minecraft_version_range,
                             forge_version       : forge_version, forge_version_range: forge_version_range,
                             loader_version_range: loader_version_range,
                             mod_id              : mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
                             mod_authors         : mod_authors, mod_description: mod_description,]

    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes(["Specification-Title"     : mod_id,
                    "Specification-Vendor"    : mod_authors,
                    "Specification-Version"   : "1",
                    "Implementation-Title"    : project.name,
                    "Implementation-Version"  : project.jar.archiveVersion,
                    "Implementation-Vendor"   : mod_authors,
                    "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")])
    }

    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
